// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjectGKNhom12_QuanLyTinTuc.Models;
using System;

namespace ProjectGKNhom12_QuanLyTinTuc.Migrations
{
    [DbContext(typeof(ApplicationDbContex))]
    [Migration("20181201070848_version02")]
    partial class version02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectGKNhom12_QuanLiTinTuc.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HoTen");

                    b.Property<int>("KieuNguoiDung");

                    b.Property<string>("MatKhau");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("ProjectGKNhom12_QuanLiTinTuc.Models.TinTuc", b =>
                {
                    b.Property<string>("MaTin")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anh");

                    b.Property<string>("MaNguoiDung");

                    b.Property<string>("MaTheLoai");

                    b.Property<DateTime>("NgayDang");

                    b.Property<string>("NoiDung");

                    b.Property<string>("TieuDe");

                    b.HasKey("MaTin");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("ProjectGKNhom12_QuanLiTinTuc.TheLoai", b =>
                {
                    b.Property<string>("MaTheLoai")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("ProjectGKNhom12_QuanLiTinTuc.Models.TinTuc", b =>
                {
                    b.HasOne("ProjectGKNhom12_QuanLiTinTuc.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.HasOne("ProjectGKNhom12_QuanLiTinTuc.TheLoai", "TheLoai")
                        .WithMany()
                        .HasForeignKey("MaTheLoai");
                });
#pragma warning restore 612, 618
        }
    }
}
